update @ 2026-07-25 16:58:36 UTC
### 3sat

- 173 pages changed
- 10 pages added
- 12 pages removed
- 365 pages unchanged

### ard

- 141 pages changed
- 8 pages added
- 6 pages removed
- 699 pages unchanged

### ndr

- 182 pages changed
- 6 pages added
- 6 pages removed
- 999 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connection.py", line 204, in _new_conn
    sock = connection.create_connection(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1106, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connection.py", line 759, in connect
    self.sock = sock = self._new_conn()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<HTTPSConnection(host='teletext.n-tv.de', port=443) at 0x7ff48436c4f0>, 'Connection to teletext.n-tv.de timed out. (connect timeout=20)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by ConnectTimeoutError(<HTTPSConnection(host='teletext.n-tv.de', port=443) at 0x7ff48436c4f0>, 'Connection to teletext.n-tv.de timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 585, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by ConnectTimeoutError(<HTTPSConnection(host='teletext.n-tv.de', port=443) at 0x7ff48436c4f0>, 'Connection to teletext.n-tv.de timed out. (connect timeout=20)'))
```
### sr

- 75 pages changed
- 10 pages added
- 5 pages removed
- 434 pages unchanged

### swr_bw

- 181 pages changed
- 7 pages added
- 18 pages removed
- 878 pages unchanged

### swr_rp

- 182 pages changed
- 7 pages added
- 15 pages removed
- 863 pages unchanged

### wdr

- 218 pages changed
- 15 pages added
- 17 pages removed
- 543 pages unchanged

### zdf

- 121 pages changed
- 12 pages added
- 49 pages removed
- 363 pages unchanged

### zdf-info

- 63 pages changed
- 3 pages added
- 34 pages removed
- 152 pages unchanged

### zdf-neo

- 64 pages changed
- 2 pages added
- 46 pages removed
- 150 pages unchanged