update @ 2026-10-08 15:16:34 UTC
### 3sat

- 274 pages changed
- 27 pages added
- 20 pages removed
- 294 pages unchanged

### ard

- 314 pages changed
- 18 pages added
- 37 pages removed
- 484 pages unchanged

### ndr

- 377 pages changed
- 11 pages added
- 4 pages removed
- 821 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 481, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/ssl.py", line 1117, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/ssl.py", line 1388, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 494, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 555, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 202, in get_html
    response = self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.22/x64/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))
```
### orf1

- 618 pages changed
- 30 pages added
- 24 pages removed
- 812 pages unchanged

### orf2

- 622 pages changed
- 26 pages added
- 24 pages removed
- 810 pages unchanged

### orf3

- 291 pages changed
- 6 pages added
- 6 pages removed
- 388 pages unchanged

### orfsportplus

- 162 pages changed
- 12 pages added
- 10 pages removed
- 211 pages unchanged

### sr

- 102 pages changed
- 2 pages added
- 1 pages removed
- 399 pages unchanged

### swr_bw

- 262 pages changed
- 16 pages added
- 28 pages removed
- 790 pages unchanged

### swr_rp

- 273 pages changed
- 34 pages added
- 10 pages removed
- 756 pages unchanged

### wdr

- 312 pages changed
- 49 pages added
- 53 pages removed
- 486 pages unchanged

### zdf

- 185 pages changed
- 38 pages added
- 36 pages removed
- 283 pages unchanged

### zdf-info

- 93 pages changed
- 1 pages added
- 23 pages removed
- 140 pages unchanged

### zdf-neo

- 101 pages changed
- 1 pages added
- 61 pages removed
- 138 pages unchanged