update @ 2026-08-16 01:19:41 UTC
### 3sat

- 204 pages changed
- 9 pages added
- 6 pages removed
- 353 pages unchanged

### ard

- 164 pages changed
- 8 pages added
- 5 pages removed
- 740 pages unchanged

### ndr

- 275 pages changed
- 16 pages added
- 7 pages removed
- 945 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 477, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 202, in get_html
    response = self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))
```
### orf1

- 390 pages changed
- 19 pages added
- 34 pages removed
- 938 pages unchanged

### orf2

- 390 pages changed
- 19 pages added
- 34 pages removed
- 939 pages unchanged

### orf3

- 191 pages changed
- 1 pages added
- 22 pages removed
- 373 pages unchanged

### orfsportplus

- 176 pages changed
- 17 pages added
- 12 pages removed
- 209 pages unchanged

### sr

- 109 pages changed
- 9 pages added
- 1 pages removed
- 414 pages unchanged

### swr_bw

- 239 pages changed
- 7 pages added
- 4 pages removed
- 851 pages unchanged

### swr_rp

- 241 pages changed
- 7 pages added
- 5 pages removed
- 817 pages unchanged

### wdr

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/update.py", line 47, in scrape
    report = scraper.download()
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 139, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/wdr.py", line 58, in iter_pages
    for sub_index, content in self._iter_sub_pages(soup.find("div", {"id": "wdrtext_inner"})):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/wdr.py", line 63, in _iter_sub_pages
    sub_page = div.find("div", {"id": f"seite_{sub_index}"})
AttributeError: 'NoneType' object has no attribute 'find'
```
### zdf

- 184 pages changed
- 44 pages added
- 26 pages removed
- 346 pages unchanged

### zdf-info

- 65 pages changed
- 7 pages added
- 164 pages unchanged

### zdf-neo

- 66 pages changed
- 7 pages added
- 152 pages unchanged