update @ 2026-08-26 08:43:24 UTC
### 3sat

- 245 pages changed
- 21 pages added
- 13 pages removed
- 276 pages unchanged

### ard

- 260 pages changed
- 6 pages added
- 33 pages removed
- 568 pages unchanged

### ndr

- 267 pages changed
- 9 pages added
- 6 pages removed
- 919 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 477, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 202, in get_html
    response = self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))
```
### orf1

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/update.py", line 47, in scrape
    report = scraper.download()
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 139, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/orf.py", line 34, in iter_pages
    menu = soup.find("div", {"class": "menu"})
AttributeError: 'NoneType' object has no attribute 'find'
```
### orf2

- 537 pages changed
- 23 pages added
- 32 pages removed
- 758 pages unchanged

### orf3

- 199 pages changed
- 6 pages added
- 2 pages removed
- 360 pages unchanged

### orfsportplus

- 167 pages changed
- 11 pages added
- 4 pages removed
- 196 pages unchanged

### sr

- 110 pages changed
- 7 pages added
- 11 pages removed
- 371 pages unchanged

### swr_bw

- 266 pages changed
- 30 pages added
- 26 pages removed
- 760 pages unchanged

### swr_rp

- 268 pages changed
- 19 pages added
- 11 pages removed
- 753 pages unchanged

### wdr

- 259 pages changed
- 46 pages added
- 20 pages removed
- 498 pages unchanged

### zdf

- 174 pages changed
- 44 pages added
- 33 pages removed
- 254 pages unchanged

### zdf-info

- 153 pages changed
- 24 pages added
- 16 pages removed
- 50 pages unchanged

### zdf-neo

- 156 pages changed
- 69 pages added
- 12 pages removed
- 62 pages unchanged