update @ 2026-06-27 03:33:06 UTC
### 3sat

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 129, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/zdf.py", line 50, in iter_pages
    date = datetime.datetime.strptime(date[:19], "%Y-%m-%dT%H:%M:%S")
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '<!DOCTYPE html>\n<ht' does not match format '%Y-%m-%dT%H:%M:%S'
```
### ard

- 355 pages changed
- 26 pages added
- 12 pages removed
- 463 pages unchanged

### ndr

- 268 pages changed
- 6 pages added
- 17 pages removed
- 934 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connection.py", line 204, in _new_conn
    sock = connection.create_connection(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1106, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connection.py", line 759, in connect
    self.sock = sock = self._new_conn()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<HTTPSConnection(host='teletext.n-tv.de', port=443) at 0x7f1342d53760>, 'Connection to teletext.n-tv.de timed out. (connect timeout=20)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by ConnectTimeoutError(<HTTPSConnection(host='teletext.n-tv.de', port=443) at 0x7f1342d53760>, 'Connection to teletext.n-tv.de timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 585, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by ConnectTimeoutError(<HTTPSConnection(host='teletext.n-tv.de', port=443) at 0x7f1342d53760>, 'Connection to teletext.n-tv.de timed out. (connect timeout=20)'))
```
### sr

- 123 pages changed
- 4 pages added
- 17 pages removed
- 409 pages unchanged

### swr_bw

- 268 pages changed
- 21 pages added
- 20 pages removed
- 802 pages unchanged

### swr_rp

- 240 pages changed
- 20 pages added
- 11 pages removed
- 830 pages unchanged

### wdr

- 168 pages changed
- 566 pages added
- 20 pages removed
- 150 pages unchanged

### zdf

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 129, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/zdf.py", line 50, in iter_pages
    date = datetime.datetime.strptime(date[:19], "%Y-%m-%dT%H:%M:%S")
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '<!DOCTYPE html>\n<ht' does not match format '%Y-%m-%dT%H:%M:%S'
```
### zdf-info

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 129, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/zdf.py", line 50, in iter_pages
    date = datetime.datetime.strptime(date[:19], "%Y-%m-%dT%H:%M:%S")
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '<!DOCTYPE html>\n<ht' does not match format '%Y-%m-%dT%H:%M:%S'
```
### zdf-neo

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 129, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/zdf.py", line 50, in iter_pages
    date = datetime.datetime.strptime(date[:19], "%Y-%m-%dT%H:%M:%S")
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '<!DOCTYPE html>\n<ht' does not match format '%Y-%m-%dT%H:%M:%S'
```