update @ 2026-08-11 16:57:25 UTC
### 3sat

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 139, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/zdf.py", line 50, in iter_pages
    date = datetime.datetime.strptime(date[:19], "%Y-%m-%dT%H:%M:%S")
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '<!DOCTYPE html>\n<ht' does not match format '%Y-%m-%dT%H:%M:%S'
```
### ard

- 313 pages changed
- 35 pages added
- 26 pages removed
- 554 pages unchanged

### ndr

- 275 pages changed
- 12 pages added
- 23 pages removed
- 915 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 477, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 202, in get_html
    response = self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))
```
### orf1

- 493 pages changed
- 21 pages added
- 27 pages removed
- 817 pages unchanged

### orf2

- 493 pages changed
- 21 pages added
- 27 pages removed
- 818 pages unchanged

### orf3

- 234 pages changed
- 9 pages added
- 4 pages removed
- 335 pages unchanged

### orfsportplus

- 145 pages changed
- 10 pages added
- 14 pages removed
- 216 pages unchanged

### sr

- 75 pages changed
- 10 pages added
- 9 pages removed
- 440 pages unchanged

### swr_bw

- 225 pages changed
- 43 pages added
- 11 pages removed
- 815 pages unchanged

### swr_rp

- 181 pages changed
- 9 pages added
- 4 pages removed
- 840 pages unchanged

### wdr

- 203 pages changed
- 14 pages added
- 15 pages removed
- 572 pages unchanged

### zdf

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 139, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/zdf.py", line 50, in iter_pages
    date = datetime.datetime.strptime(date[:19], "%Y-%m-%dT%H:%M:%S")
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '<!DOCTYPE html>\n<ht' does not match format '%Y-%m-%dT%H:%M:%S'
```
### zdf-info

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 139, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/zdf.py", line 50, in iter_pages
    date = datetime.datetime.strptime(date[:19], "%Y-%m-%dT%H:%M:%S")
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '<!DOCTYPE html>\n<ht' does not match format '%Y-%m-%dT%H:%M:%S'
```
### zdf-neo

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 139, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/zdf.py", line 50, in iter_pages
    date = datetime.datetime.strptime(date[:19], "%Y-%m-%dT%H:%M:%S")
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '<!DOCTYPE html>\n<ht' does not match format '%Y-%m-%dT%H:%M:%S'
```