update @ 2026-08-17 01:17:15 UTC
### 3sat

- 208 pages changed
- 6 pages added
- 7 pages removed
- 337 pages unchanged

### ard

- 175 pages changed
- 11 pages added
- 10 pages removed
- 709 pages unchanged

### ndr

- 271 pages changed
- 11 pages added
- 15 pages removed
- 951 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 477, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 202, in get_html
    response = self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))
```
### orf1

- 417 pages changed
- 17 pages added
- 34 pages removed
- 925 pages unchanged

### orf2

- 417 pages changed
- 17 pages added
- 34 pages removed
- 926 pages unchanged

### orf3

- 152 pages changed
- 4 pages added
- 12 pages removed
- 402 pages unchanged

### orfsportplus

- 168 pages changed
- 13 pages added
- 19 pages removed
- 208 pages unchanged

### sr

- 119 pages changed
- 7 pages added
- 1 pages removed
- 410 pages unchanged

### swr_bw

- 209 pages changed
- 8 pages added
- 16 pages removed
- 871 pages unchanged

### swr_rp

- 198 pages changed
- 11 pages added
- 9 pages removed
- 849 pages unchanged

### wdr

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/update.py", line 47, in scrape
    report = scraper.download()
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 139, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/wdr.py", line 58, in iter_pages
    for sub_index, content in self._iter_sub_pages(soup.find("div", {"id": "wdrtext_inner"})):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/wdr.py", line 63, in _iter_sub_pages
    sub_page = div.find("div", {"id": f"seite_{sub_index}"})
AttributeError: 'NoneType' object has no attribute 'find'
```
### zdf

- 145 pages changed
- 18 pages added
- 23 pages removed
- 389 pages unchanged

### zdf-info

- 69 pages changed
- 3 pages added
- 4 pages removed
- 157 pages unchanged

### zdf-neo

- 70 pages changed
- 2 pages added
- 4 pages removed
- 152 pages unchanged