update @ 2026-09-25 19:52:37 UTC
### 3sat

- 158 pages changed
- 18 pages added
- 25 pages removed
- 390 pages unchanged

### ard

- 272 pages changed
- 14 pages added
- 19 pages removed
- 601 pages unchanged

### ndr

- 268 pages changed
- 9 pages added
- 19 pages removed
- 922 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 481, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 494, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 555, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 202, in get_html
    response = self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))
```
### orf1

- 410 pages changed
- 22 pages added
- 7 pages removed
- 1009 pages unchanged

### orf2

- 418 pages changed
- 14 pages added
- 7 pages removed
- 1017 pages unchanged

### orf3

- 179 pages changed
- 1 pages added
- 1 pages removed
- 508 pages unchanged

### orfsportplus

- 145 pages changed
- 6 pages added
- 2 pages removed
- 226 pages unchanged

### sr

- 72 pages changed
- 3 pages added
- 2 pages removed
- 435 pages unchanged

### swr_bw

- 235 pages changed
- 15 pages added
- 12 pages removed
- 836 pages unchanged

### swr_rp

- 228 pages changed
- 19 pages added
- 12 pages removed
- 825 pages unchanged

### wdr

- 244 pages changed
- 26 pages added
- 32 pages removed
- 588 pages unchanged

### zdf

- 150 pages changed
- 25 pages added
- 29 pages removed
- 312 pages unchanged

### zdf-info

- 76 pages changed
- 5 pages added
- 23 pages removed
- 152 pages unchanged

### zdf-neo

- 71 pages changed
- 8 pages added
- 12 pages removed
- 137 pages unchanged