update @ 2026-08-30 04:04:08 UTC
### 3sat

- 211 pages changed
- 44 pages added
- 39 pages removed
- 269 pages unchanged

### ard

- 226 pages changed
- 18 pages added
- 32 pages removed
- 616 pages unchanged

### ndr

- 292 pages changed
- 33 pages added
- 45 pages removed
- 907 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 477, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 202, in get_html
    response = self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.21/x64/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))
```
### orf1

- 556 pages changed
- 39 pages added
- 43 pages removed
- 768 pages unchanged

### orf2

- 556 pages changed
- 39 pages added
- 43 pages removed
- 769 pages unchanged

### orf3

- 186 pages changed
- 16 pages added
- 27 pages removed
- 352 pages unchanged

### orfsportplus

- 191 pages changed
- 9 pages added
- 9 pages removed
- 200 pages unchanged

### sr

- 117 pages changed
- 10 pages added
- 10 pages removed
- 367 pages unchanged

### swr_bw

- 230 pages changed
- 9 pages added
- 9 pages removed
- 834 pages unchanged

### swr_rp

- 236 pages changed
- 4 pages added
- 7 pages removed
- 819 pages unchanged

### wdr

- 301 pages changed
- 29 pages added
- 19 pages removed
- 531 pages unchanged

### zdf

- 147 pages changed
- 76 pages added
- 41 pages removed
- 323 pages unchanged

### zdf-info

- 104 pages changed
- 28 pages added
- 6 pages removed
- 107 pages unchanged

### zdf-neo

- 103 pages changed
- 76 pages added
- 3 pages removed
- 105 pages unchanged