update @ 2026-05-06 10:20:09 UTC
### 3sat

- 262 pages changed
- 19 pages added
- 35 pages removed
- 276 pages unchanged

### ard

- 342 pages changed
- 22 pages added
- 44 pages removed
- 521 pages unchanged

### ndr

- 281 pages changed
- 22 pages added
- 14 pages removed
- 955 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/update.py", line 42, in scrape
    report = scraper.download()
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 129, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/ntv.py", line 36, in iter_pages
    data = self.get_html(url).json()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
### sr

- 140 pages changed
- 7 pages added
- 19 pages removed
- 345 pages unchanged

### swr_bw

- 281 pages changed
- 29 pages added
- 6 pages removed
- 672 pages unchanged

### swr_rp

- 268 pages changed
- 18 pages added
- 15 pages removed
- 659 pages unchanged

### wdr

- 245 pages changed
- 15 pages added
- 22 pages removed
- 602 pages unchanged

### zdf

- 178 pages changed
- 56 pages added
- 17 pages removed
- 270 pages unchanged

### zdf-info

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/response.py", line 903, in _error_catcher
    yield
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/response.py", line 1049, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(13410 bytes read, 42 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/response.py", line 1149, in read
    data = self._raw_read(amt)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/response.py", line 1027, in _raw_read
    with self._error_catcher():
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/response.py", line 927, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(13410 bytes read, 42 more expected)', IncompleteRead(13410 bytes read, 42 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(13410 bytes read, 42 more expected)', IncompleteRead(13410 bytes read, 42 more expected))
```
### zdf-neo

- 164 pages changed
- 78 pages added
- 5 pages removed
- 58 pages unchanged