update @ 2026-08-16 08:29:55 UTC
### 3sat

- 220 pages changed
- 19 pages added
- 39 pages removed
- 307 pages unchanged

### ard

- 176 pages changed
- 23 pages added
- 38 pages removed
- 698 pages unchanged

### ndr

- 245 pages changed
- 42 pages added
- 21 pages removed
- 970 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 477, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 202, in get_html
    response = self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))
```
### orf1

```
Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/update.py", line 47, in scrape
    report = scraper.download()
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 139, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/sources/orf.py", line 34, in iter_pages
    menu = soup.find("div", {"class": "menu"})
AttributeError: 'NoneType' object has no attribute 'find'
```
### orf2

- 499 pages changed
- 49 pages added
- 21 pages removed
- 828 pages unchanged

### orf3

- 188 pages changed
- 6 pages added
- 5 pages removed
- 372 pages unchanged

### orfsportplus

- 172 pages changed
- 10 pages added
- 18 pages removed
- 212 pages unchanged

### sr

- 139 pages changed
- 20 pages added
- 26 pages removed
- 367 pages unchanged

### swr_bw

- 260 pages changed
- 18 pages added
- 26 pages removed
- 811 pages unchanged

### swr_rp

- 245 pages changed
- 16 pages added
- 20 pages removed
- 800 pages unchanged

### wdr

- 18 pages changed
- 826 pages added

### zdf

- 188 pages changed
- 72 pages added
- 66 pages removed
- 320 pages unchanged

### zdf-info

- 156 pages changed
- 27 pages added
- 8 pages removed
- 72 pages unchanged

### zdf-neo

- 148 pages changed
- 65 pages added
- 7 pages removed
- 70 pages unchanged