update @ 2026-08-14 01:59:15 UTC
### 3sat

- 233 pages changed
- 7 pages added
- 22 pages removed
- 341 pages unchanged

### ard

- 266 pages changed
- 13 pages added
- 18 pages removed
- 631 pages unchanged

### ndr

- 237 pages changed
- 2 pages added
- 15 pages removed
- 977 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 477, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 564, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2026/teletext-archive-2026/src/scraper.py", line 202, in get_html
    response = self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='teletext.n-tv.de', port=443): Max retries exceeded with url: /teletext-api/100/0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1017)')))
```
### orf1

- 460 pages changed
- 19 pages added
- 19 pages removed
- 876 pages unchanged

### orf2

- 458 pages changed
- 26 pages added
- 17 pages removed
- 875 pages unchanged

### orf3

- 179 pages changed
- 9 pages added
- 4 pages removed
- 402 pages unchanged

### orfsportplus

- 172 pages changed
- 11 pages added
- 11 pages removed
- 212 pages unchanged

### sr

- 70 pages changed
- 7 pages added
- 2 pages removed
- 452 pages unchanged

### swr_bw

- 118 pages changed
- 4 pages added
- 19 pages removed
- 944 pages unchanged

### swr_rp

- 100 pages changed
- 3 pages added
- 10 pages removed
- 931 pages unchanged

### wdr

- 209 pages changed
- 25 pages added
- 12 pages removed
- 596 pages unchanged

### zdf

- 146 pages changed
- 28 pages added
- 21 pages removed
- 371 pages unchanged

### zdf-info

- 73 pages changed
- 3 pages added
- 1 pages removed
- 147 pages unchanged

### zdf-neo

- 73 pages changed
- 3 pages added
- 1 pages removed
- 148 pages unchanged